spring:
  datasource:
    url: jdbc:mysql://localhost:3306/w?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8880
  tomcat:
    uri-encoding: UTF-8
  ip: localhost

mybatis:
  mapper-locations: classpath:/mappers/*.xml
mybatis-plus:
  type-aliases-package: com.baidu.class01.pojo
  map-underscore-to-camel-case: false


